name: Main workflow

on:
  push:
    branches: [ '**', master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Create JSON (Credentials)
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "config.json"
        json: ${{ secrets.CONFIG_JSON }}
        dir: 'DRN-Console/bin/Debug/'

    - name: Test
      run: dotnet test --no-build --verbosity normal
